spring:
  application:
    name: poc
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

management:
  # Enable `/actuator/health/readiness` and `/actuator/health/liveness` endpoints
#  endpoint:
#    health:
#      probes:
#        enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: health,prometheus
#  metrics:
#    distribution:
##       For Exemplars to work we need histogram buckets
#      percentiles-histogram:
#        http:
#          server:
#            requests: true
  tracing:
    sampling:
      # All traces should be sent to latency analysis tool
      probability: 1
#  zipkin:
#    tracing:
#      endpoint: http://tempo.winvagrant.ilionx.cloud:9411/api/v2/spans
server:
  port : 8081

jdbc:
  # includes: [ ]
  includes:
    - QUERY
  datasource-proxy:
    include-parameter-values: true

